VCの接続/切断時のデータ更新を実装
starkoka/Tasclear pull request #4
Opened 2023-08-14 08:33 UTC by starkoka

タイトルの通り

2023-08-14 12:07 UTC, yukipeti approved these changes
大丈夫だと思う！多分！

2023-08-14 19:21 UTC, NXVZBGBFBEN requested changes
ごめん，ESLint/Prettierに関する説明を十分にしていなかったのと，コミット時の自動チェック設定について完全に忘れていた．(→ フォーマットがごちゃごちゃ，静的解析が効いてない)
わかりやすく(?)説明を入れたつもりなので確認してもらえたらありがたいです．

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on main.js
>  const db = require("./functions/db.js");
未使用かも

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on main.js
> +const recordVC = require('./functions/recordVC.js')
セミコロン抜け

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on main.js
l.2 セミコロン抜け

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on main.js
l.27 の内容と l.16 の内容が重複している...?

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on main.js
l.80 もみ消すよりはログに流したほうがよさそうではあるけど，任せます

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +const system = require('./logsystem.js');
未使用

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +        return await userData.makeUserData(userId);
``await``が冗長な気がする

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +    else{
ここ``else``節である必要がない気がする
違ってたら怒ってください

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +        if(date.toFormat("YYYYMMDD") !== user.lastUpdate.toFormat("YYYYMMDD")) {　//同じ日
全角スペースが紛れ込んでいる(``　//同じ日``)

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +                }
変数``i``は40行目ですでに定義されているはず

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +                }
再宣言になってる

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/userData.js
> +    return await userData.getUser(userId);
``await``が冗長かも

2023-08-14 19:21 UTC, NXVZBGBFBEN commented on functions/recordVC.js
> +const system = require('./logsystem.js');
未使用

2023-08-15 02:37 UTC, starkoka commented on main.js
正直これに関しては、こちら側の問題ではない場合がほとんど(DiscordAPIのエラー or 処理中にユーザーがメッセージを消した)なので、もみ消しました(統合管理botもそうなってる)

2023-08-15 02:38 UTC, starkoka commented on functions/userData.js
> +    else{
確かにーー

2023-08-15 02:40 UTC, starkoka commented on functions/userData.js
> +    return await userData.getUser(userId);
これ詳しく

2023-08-15 02:41 UTC, starkoka commented on functions/recordVC.js
> +const system = require('./logsystem.js');
やべ、ログ流すの忘れてた。まあ後でやろう

2023-08-15 02:47 UTC, merged