/studydata 仮実装
starkoka/Tasclear pull request #6
Opened 2023-08-15 06:30 UTC by starkoka

今後カードを画像にしたい

2023-08-15 08:09 UTC, yukipeti approved these changes
よくわかんないけど大丈夫なんじゃないかな！うん！

2023-08-15 20:41 UTC, NXVZBGBFBEN requested changes
すこしだけ

2023-08-15 20:41 UTC, NXVZBGBFBEN commented on functions/userData.js
> +const {StringSelectMenuBuilder, StringSelectMenuOptionBuilder, EmbedBuilder, ActionRowBuilder, version} = require("discord.js");
``EmbedBuilder``以外は未使用

2023-08-15 20:41 UTC, NXVZBGBFBEN commented on functions/userData.js
>  const system = require('./logsystem.js');
``system``は未使用

2023-08-15 20:41 UTC, NXVZBGBFBEN commented on functions/userData.js
> +const packageVer = require("../package.json");
未使用...?

2023-08-16 05:49 UTC, NXVZBGBFBEN approved these changes
あっｐろゔぇ

2023-08-16 13:00 UTC, merged